### PR TITLE
docs: fix typo in yarn install options

### PR DESCRIPTION
**Pull request by contigen**
The package is supposed to be a devDependency; yarn add flag was incorrect, installs it as a dependency.

### CODE REVIEW

**Review by kettanaito — APPROVED** [review]
A good point. Thanks for updating this, @contigen!

**Comment by kettanaito** [comment]
Welcome to the contributors! 🎉

**Comment by contigen** [comment]
Thanks

**Comment by kettanaito** [comment]
## Released: v0.13.1 🎉

This has been released in v0.13.1!

- 📄 [**Release notes**](https://github.com/mswjs/data/releases/tag/v0.13.1)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/data/v/0.13.1)

Make sure to always update to the latest version (`npm i @mswjs/data@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Pull request merged**
